/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as LibyanInvestmentRouteImport } from './routes/libyan-investment'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DataImportRouteImport } from './routes/data-import'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentStatementAgentIdRouteImport } from './routes/agent-statement.$agentId'
import { Route as ApiPublicHooksBackupRouteImport } from './routes/api/public/hooks/backup'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const LibyanInvestmentRoute = LibyanInvestmentRouteImport.update({
  id: '/libyan-investment',
  path: '/libyan-investment',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DataImportRoute = DataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentStatementAgentIdRoute = AgentStatementAgentIdRouteImport.update({
  id: '/agent-statement/$agentId',
  path: '/agent-statement/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackupRoute = ApiPublicHooksBackupRouteImport.update({
  id: '/api/public/hooks/backup',
  path: '/api/public/hooks/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/companies': typeof CompaniesRoute
  '/data-import': typeof DataImportRoute
  '/expenses': typeof ExpensesRoute
  '/flights': typeof FlightsRoute
  '/investors': typeof InvestorsRoute
  '/libyan-investment': typeof LibyanInvestmentRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/submit': typeof SubmitRoute
  '/agent-statement/$agentId': typeof AgentStatementAgentIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/companies': typeof CompaniesRoute
  '/data-import': typeof DataImportRoute
  '/expenses': typeof ExpensesRoute
  '/flights': typeof FlightsRoute
  '/investors': typeof InvestorsRoute
  '/libyan-investment': typeof LibyanInvestmentRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/submit': typeof SubmitRoute
  '/agent-statement/$agentId': typeof AgentStatementAgentIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accounts': typeof AccountsRoute
  '/approvals': typeof ApprovalsRoute
  '/companies': typeof CompaniesRoute
  '/data-import': typeof DataImportRoute
  '/expenses': typeof ExpensesRoute
  '/flights': typeof FlightsRoute
  '/investors': typeof InvestorsRoute
  '/libyan-investment': typeof LibyanInvestmentRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/submit': typeof SubmitRoute
  '/agent-statement/$agentId': typeof AgentStatementAgentIdRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/accounts'
    | '/approvals'
    | '/companies'
    | '/data-import'
    | '/expenses'
    | '/flights'
    | '/investors'
    | '/libyan-investment'
    | '/merchants'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/submissions'
    | '/submit'
    | '/agent-statement/$agentId'
    | '/api/public/hooks/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/accounts'
    | '/approvals'
    | '/companies'
    | '/data-import'
    | '/expenses'
    | '/flights'
    | '/investors'
    | '/libyan-investment'
    | '/merchants'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/submissions'
    | '/submit'
    | '/agent-statement/$agentId'
    | '/api/public/hooks/backup'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/accounts'
    | '/approvals'
    | '/companies'
    | '/data-import'
    | '/expenses'
    | '/flights'
    | '/investors'
    | '/libyan-investment'
    | '/merchants'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/submissions'
    | '/submit'
    | '/agent-statement/$agentId'
    | '/api/public/hooks/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccountsRoute: typeof AccountsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CompaniesRoute: typeof CompaniesRoute
  DataImportRoute: typeof DataImportRoute
  ExpensesRoute: typeof ExpensesRoute
  FlightsRoute: typeof FlightsRoute
  InvestorsRoute: typeof InvestorsRoute
  LibyanInvestmentRoute: typeof LibyanInvestmentRoute
  MerchantsRoute: typeof MerchantsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRoute
  SubmitRoute: typeof SubmitRoute
  AgentStatementAgentIdRoute: typeof AgentStatementAgentIdRoute
  ApiPublicHooksBackupRoute: typeof ApiPublicHooksBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libyan-investment': {
      id: '/libyan-investment'
      path: '/libyan-investment'
      fullPath: '/libyan-investment'
      preLoaderRoute: typeof LibyanInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-import': {
      id: '/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof DataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-statement/$agentId': {
      id: '/agent-statement/$agentId'
      path: '/agent-statement/$agentId'
      fullPath: '/agent-statement/$agentId'
      preLoaderRoute: typeof AgentStatementAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup': {
      id: '/api/public/hooks/backup'
      path: '/api/public/hooks/backup'
      fullPath: '/api/public/hooks/backup'
      preLoaderRoute: typeof ApiPublicHooksBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AccountsRoute: AccountsRoute,
  ApprovalsRoute: ApprovalsRoute,
  CompaniesRoute: CompaniesRoute,
  DataImportRoute: DataImportRoute,
  ExpensesRoute: ExpensesRoute,
  FlightsRoute: FlightsRoute,
  InvestorsRoute: InvestorsRoute,
  LibyanInvestmentRoute: LibyanInvestmentRoute,
  MerchantsRoute: MerchantsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRoute,
  SubmitRoute: SubmitRoute,
  AgentStatementAgentIdRoute: AgentStatementAgentIdRoute,
  ApiPublicHooksBackupRoute: ApiPublicHooksBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
