INSERT INTO public.system_dropdown_options (category, value, is_active) VALUES
  ('agent_tier', 'A', true),
  ('agent_tier', 'B', true),
  ('agent_tier', 'C', true),
  ('airline', 'إير كايرو', true),
  ('airline', 'الأفريقية', true),
  ('airline', 'البراق', true),
  ('airline', 'البرنيق', true),
  ('airline', 'الليبية', true),
  ('airline', 'تاج', true),
  ('airline', 'مصر للطيران', true),
  ('airport', 'القاهرة', true),
  ('airport', 'برج العرب', true),
  ('authority', 'جمرك بري', true),
  ('authority', 'مطار القاهرة', true),
  ('authority', 'مطار برج العرب', true),
  ('departure_from', 'جمرك بري', true),
  ('departure_from', 'مطار القاهرة', true),
  ('departure_from', 'مطار برج العرب', true),
  ('destination', 'بنغازي', true),
  ('destination', 'سبها', true),
  ('destination', 'طرابلس', true),
  ('destination', 'مصراته', true),
  ('execution_status', 'بطيء', true),
  ('execution_status', 'رفض أمني', true),
  ('execution_status', 'سريع', true),
  ('operation_status', 'قيد التنفيذ', true),
  ('operation_status', 'ملغي', true),
  ('operation_status', 'منفذ', true),
  ('passenger_type', 'رضع', true),
  ('passenger_type', 'سيدات', true),
  ('passenger_type', 'طفل تحت 12', true),
  ('passenger_type', 'طفل تحت 8', true),
  ('service_kind', 'استثمار', true),
  ('service_kind', 'استثمار بري', true),
  ('service_kind', 'بري شغل كامل', true),
  ('service_kind', 'بنغازي شغل كامل', true),
  ('service_kind', 'تأشيرة طرابلس', true),
  ('service_kind', 'تذكرة', true),
  ('service_kind', 'تذكرة واستثمار', true),
  ('service_kind', 'خدمات أخرى', true),
  ('service_kind', 'سبها شغل كامل', true),
  ('service_kind', 'طرابلس شغل كامل', true),
  ('service_kind', 'مصراته تنسيق', true),
  ('service_kind', 'مصراته شغل كامل', true),
  ('service_kind', 'موافقة أمنية', true),
  ('service_kind', 'موافقة واستثمار بري', true),
  ('service_kind', 'نقل ........', true),
  ('service_kind', 'نقل بري (طبرق واجدابيا)', true),
  ('service_kind', 'نقل طرابلس', true),
  ('service_kind', 'نقل عن طريق سبها', true),
  ('service_kind', 'نقل مصراته', true),
  ('service_type', 'استثمار', true),
  ('service_type', 'استثمار بري', true),
  ('service_type', 'استثمار عسكري', true),
  ('service_type', 'استثمار ليبي', true),
  ('service_type', 'بري شغل كامل', true),
  ('service_type', 'بنغازي شغل كامل', true),
  ('service_type', 'تأشيرة طرابلس', true),
  ('service_type', 'تذاكر طيران', true),
  ('service_type', 'تذكرة', true),
  ('service_type', 'تذكرة طيران', true),
  ('service_type', 'تذكرة واستثمار', true),
  ('service_type', 'خدمات أخرى', true),
  ('service_type', 'سبها شغل كامل', true),
  ('service_type', 'طرابلس شغل كامل', true),
  ('service_type', 'مصراته تنسيق', true),
  ('service_type', 'مصراته شغل كامل', true),
  ('service_type', 'موافقة أمنية', true),
  ('service_type', 'موافقة واستثمار بري', true),
  ('service_type', 'نقل ........', true),
  ('service_type', 'نقل بري (طبرق واجدابيا)', true),
  ('service_type', 'نقل طرابلس', true),
  ('service_type', 'نقل عن طريق سبها', true),
  ('service_type', 'نقل مصراته', true),
  ('submission_notes', 'رضيع', true),
  ('submission_notes', 'سيدات', true),
  ('submission_notes', 'طفل تحت 12', true),
  ('submission_notes', 'طفل تحت 8', true),
  ('submission_status', 'بطيء', true),
  ('submission_status', 'رفض أمني', true),
  ('submission_status', 'سريع', true)
ON CONFLICT (category, value) DO NOTHING;